"""
Resul Çetin portfolio — the hero: a cine lens that mechanically transforms
into a 35 mm film reel (and back). Storyboard: docs/morph-storyboard.md.

Run headless:
    /Applications/Blender.app/Contents/MacOS/Blender -b --factory-startup \
        --python tools/hero.py -- --out models/hero.glb

    # storyboard contact frames of the transformation (not exported):
    ... --python tools/hero.py -- --out /tmp/x.glb --frames /tmp/frames

How the transformation stays robust:
  * Every morphing part is generated by one function for BOTH states (lens
    and reel) with identical vertex count and order; the reel state is stored
    as a shape key named "Reel". No modifiers on morphing meshes — they are
    built final, so the exporter never has to apply anything.
  * One scene-wide animation, exported as a single glTF clip "LensToReel".
    Frame 0 = lens, frame END = reel. The web scrubs it forward and backward.
  * Blades: Hero_BladePivot_NN (moved by the clip) → Hero_Blade_NN (rotated
    by the web to open the iris). The clip assumes the iris is fully open
    (child rotated by OPEN_DEG) — the web holds open = 1 during the morph.

Web contract (main.js): Hero_Blade_NN, Hero_Glass (front element), inner
radius ≥ 1.06 and nothing between y = 0.1 and 0.45 inside the lens barrel
(the featured-project panel sits there).
"""

import argparse
import math
import os
import sys

import bmesh
import bpy
from mathutils import Matrix, Vector

FPS = 24
END = 120                      # clip length in frames (5 s at 24 fps)
N_BLADES = 9
OPEN_DEG = 55                  # iris fully open = blade child rotated by this
PIVOT_R = 1.0
FONT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fonts", "IBMPlexMono-Medium.ttf")


# ================================================================ plumbing

def parse_args():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    p = argparse.ArgumentParser()
    p.add_argument("--out", required=True)
    p.add_argument("--frames", help="folder for storyboard PNGs of the morph")
    p.add_argument("--preview", help="single PNG of the lens (frame 0, iris half open)")
    p.add_argument("--no-draco", action="store_true")
    p.add_argument("--front", action="store_true", help="frames from straight ahead, blade section only")
    p.add_argument("--video", help="render the whole morph to an MP4 (preview only)")
    return p.parse_args(argv)


def reset_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.name = "LensToReel"
    scene.render.fps = FPS
    scene.frame_start, scene.frame_end = 0, END
    return scene


def pbr_material(name, color=(1, 1, 1), metallic=0.0, roughness=0.4,
                 transmission=0.0, ior=1.45, emission=None, emission_strength=0.0):
    mat = bpy.data.materials.new(name)
    if mat.node_tree is None:
        mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = (*color, 1.0)
    bsdf.inputs["Metallic"].default_value = metallic
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["IOR"].default_value = ior
    bsdf.inputs["Transmission Weight"].default_value = transmission
    if emission:
        bsdf.inputs["Emission Color"].default_value = (*emission, 1.0)
        bsdf.inputs["Emission Strength"].default_value = emission_strength
    return mat


def empty(name, parent=None, location=(0, 0, 0)):
    obj = bpy.data.objects.new(name, None)
    bpy.context.scene.collection.objects.link(obj)
    obj.parent = parent
    obj.location = location
    return obj


def mesh_from(name, verts, faces, material, parent, smooth=True):
    me = bpy.data.meshes.new(name)
    me.from_pydata(verts, [], faces)
    me.validate()
    # consistent outward normals (flips face winding only; vertex order is kept,
    # so the Reel shape key built from the same generator still lines up)
    bm = bmesh.new()
    bm.from_mesh(me)
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    bm.to_mesh(me)
    bm.free()
    me.update()
    obj = bpy.data.objects.new(name, me)
    bpy.context.scene.collection.objects.link(obj)
    for poly in me.polygons:
        poly.use_smooth = smooth
    if material:
        me.materials.append(material)
    obj.parent = parent
    return obj


def add_reel_key(obj, reel_verts):
    """Store the reel state as shape key "Reel" (same vertex order as base)."""
    assert len(reel_verts) == len(obj.data.vertices), obj.name
    obj.shape_key_add(name="Basis", from_mix=False)
    key = obj.shape_key_add(name="Reel", from_mix=False)
    for i, co in enumerate(reel_verts):
        key.data[i].co = co
    return key


# ================================================================ animation

def keys(target, path, pairs, index=-1):
    """pairs: [(frame, value), ...] — value is a scalar or a tuple."""
    for frame, value in pairs:
        if index >= 0 or not isinstance(value, (tuple, list)):
            if index >= 0:
                getattr(target, path)[index] = value
            else:
                setattr(target, path, value)
        else:
            setattr(target, path, value)
        target.keyframe_insert(path, index=index, frame=frame)


def morph(obj, f0, f1):
    """Animate the Reel shape key 0 → 1 between two frames."""
    kb = obj.data.shape_keys.key_blocks["Reel"]
    keys(kb, "value", [(0, 0.0), (f0, 0.0), (f1, 1.0), (END, 1.0)])


def telescope(obj, dy, base=None):
    """Slide along the lens axis and back: separate, hold, rejoin."""
    x, y, z = base if base else tuple(obj.location)
    keys(obj, "location", [(0, (x, y, z)), (12, (x, y, z)), (40, (x, y + dy, z)),
                           (90, (x, y + dy, z)), (114, (x, y, z)), (END, (x, y, z))])


# ================================================================ geometry
# Each generator returns (verts, faces) with a topology that depends only on
# its integer arguments, so the lens and reel states always match.

def lathe(profile, steps=128):
    """Revolve a closed (radius, y) profile around the Y axis."""
    n = len(profile)
    verts = []
    for i in range(steps):
        th = i / steps * math.tau
        s, c = math.sin(th), math.cos(th)
        for r, y in profile:
            verts.append((s * r, y, c * r))
    faces = []
    for i in range(steps):
        a, b = i * n, ((i + 1) % steps) * n
        for j in range(n):
            k = (j + 1) % n
            faces.append((a + j, a + k, b + k, b + j))
    return verts, faces


def strip_solid(outer, inner, y0, y1):
    """A flat plate from two matching polylines (outer[i] ↔ inner[i]) in XZ,
    extruded between y0 and y1. Quads only, so it morphs cleanly."""
    n = len(outer)
    ring = outer + inner[::-1]                      # closed outline
    m = len(ring)
    verts = [(x, y0, z) for x, z in ring] + [(x, y1, z) for x, z in ring]
    faces = []
    for i in range(n - 1):                          # front and back faces as quad strips
        o0, o1 = i, i + 1
        i0, i1 = m - 1 - i, m - 2 - i
        faces.append((o0, o1, i1, i0))
        faces.append((m + i0, m + i1, m + o1, m + o0))
    for i in range(m):                              # side walls
        j = (i + 1) % m
        faces.append((i, m + i, m + j, j))
    return verts, faces


def blade_polylines(segments=40):
    """Crescent for blade 0 (pivot at +X), returns (outer, inner) in XZ, world."""
    pivot = Vector((PIVOT_R, 0.0))
    centre = Vector((0.32, 0.78))
    r = (pivot - centre).length
    a0 = math.atan2(pivot.y - centre.y, pivot.x - centre.x)
    sweep = math.radians(118)
    outer, inner = [], []
    for k in range(segments + 1):
        s = k / segments
        a = a0 - sweep * s
        p = centre + Vector((math.cos(a), math.sin(a))) * r
        n = (p - centre).normalized()
        w = 0.06 + 0.44 * math.sin(math.pi * min(s * 1.08, 1.0)) ** 0.65
        outer.append(p + n * w * 0.5)
        inner.append(p - n * w * 0.5)
    return outer, inner


def spoke_polylines(theta, segments=40, r0=0.38, r1=1.72, reverse=False, flip=False):
    """Straight reel spoke along angle theta (XZ, world), same point count as a
    blade. reverse: run rim → hub; flip: swap which side counts as "outer"."""
    d = Vector((math.cos(theta), math.sin(theta)))     # same convention as blade pivots
    nrm = Vector((-d.y, d.x)) * (-1.0 if flip else 1.0)
    outer, inner = [], []
    for k in range(segments + 1):
        s = k / segments
        u = 1.0 - s if reverse else s
        c = d * (r0 + (r1 - r0) * u)
        hw = 0.045 + 0.03 * math.sin(math.pi * s) ** 0.5
        outer.append(c + nrm * hw)
        inner.append(c - nrm * hw)
    return outer, inner


def grip_mesh(r_outer, r_edge, r_inner, y0, y1, ridge, groove=0.0, rings=8, ribs=96, seg=4):
    """Focus grip ↔ film roll. A ridged outer cylinder, two caps made of
    concentric rings (grooves = wound film layers when groove > 0) and an
    inner wall. Topology depends only on rings/ribs/seg."""
    steps = ribs * seg
    ys = [y0, y0 + 0.012, y1 - 0.012, y1]
    verts = []
    for j, y in enumerate(ys):                       # outer surface rows
        edge = j in (0, len(ys) - 1)
        for i in range(steps):
            th = i / steps * math.tau
            rr = r_edge if edge else r_outer + ridge * (0.5 + 0.5 * math.cos(th * ribs)) ** 3
            verts.append((math.sin(th) * rr, y, math.cos(th) * rr))
    cap_start = {}
    for side, y in (("front", y0), ("back", y1)):    # cap rings, outer → inner
        cap_start[side] = len(verts)
        sign = -1.0 if side == "front" else 1.0
        for k in range(1, rings + 1):
            rr = r_edge + (r_inner - r_edge) * k / rings
            dy = sign * groove * (k % 2)
            for i in range(steps):
                th = i / steps * math.tau
                verts.append((math.sin(th) * rr, y + dy, math.cos(th) * rr))
    faces = []
    quad = lambda a, b, i: (a + i, a + (i + 1) % steps, b + (i + 1) % steps, b + i)
    for j in range(len(ys) - 1):
        for i in range(steps):
            faces.append(quad(j * steps, (j + 1) * steps, i))
    back_out = (len(ys) - 1) * steps
    for side, outer_row in (("front", 0), ("back", back_out)):
        prev = outer_row
        for k in range(rings):
            ring = cap_start[side] + k * steps
            for i in range(steps):
                faces.append(quad(prev, ring, i))
            prev = ring
    f_in = cap_start["front"] + (rings - 1) * steps
    b_in = cap_start["back"] + (rings - 1) * steps
    for i in range(steps):                           # inner wall
        faces.append(quad(f_in, b_in, i))
    return verts, faces


def ellipsoid(sx, sy, sz, cy, u=64, v=24):
    """UV-sphere-topology ellipsoid centred at (0, cy, 0)."""
    verts = [(0.0, cy + sy, 0.0)]
    for j in range(1, v):
        phi = math.pi * j / v
        for i in range(u):
            th = math.tau * i / u
            verts.append((math.sin(phi) * math.sin(th) * sx, cy + math.cos(phi) * sy,
                          math.sin(phi) * math.cos(th) * sz))
    verts.append((0.0, cy - sy, 0.0))
    faces = []
    last = len(verts) - 1
    for i in range(u):
        faces.append((0, 1 + (i + 1) % u, 1 + i))
    for j in range(v - 2):
        a, b = 1 + j * u, 1 + (j + 1) * u
        for i in range(u):
            k = (i + 1) % u
            faces.append((a + i, a + k, b + k, b + i))
    base = 1 + (v - 2) * u
    for i in range(u):
        faces.append((base + i, base + (i + 1) % u, last))
    return verts, faces


# ================================================================ engraving

def glyph(ch, size, font, material):
    bpy.ops.object.text_add()
    t = bpy.context.object
    t.data.body = ch
    t.data.font = font
    t.data.size = size
    t.data.extrude = 0.0025
    t.data.resolution_u = 3
    t.data.align_x = "CENTER"
    t.data.align_y = "CENTER"
    t.data.materials.append(material)
    return t


def join_as(name, objs, parent):
    bpy.ops.object.select_all(action="DESELECT")
    for o in objs:
        o.select_set(True)
        bpy.context.view_layer.objects.active = o
        bpy.ops.object.convert(target="MESH")
    for o in objs:
        o.select_set(True)
    bpy.context.view_layer.objects.active = objs[0]
    bpy.ops.object.join()
    obj = bpy.context.object
    # the joined mesh inherits the first glyph's origin; move it to the lens
    # axis so scaling/animation happens about the centre, not about one letter
    bpy.context.scene.cursor.location = (0.0, 0.0, 0.0)
    bpy.ops.object.origin_set(type="ORIGIN_CURSOR")
    obj.name = name
    obj.parent = parent
    return obj


def engrave_front(text, font, material, parent, radius=1.215, y=-0.3345, size=0.062, start_deg=-118):
    adv = size * 0.6 / radius
    objs = []
    for k, ch in enumerate(text):
        if ch == " ":
            continue
        phi = math.radians(start_deg) + k * adv
        g = glyph(ch, size, font, material)
        g.location = (math.sin(phi) * radius, y, math.cos(phi) * radius)
        g.rotation_euler = (math.pi / 2, phi, 0)
        objs.append(g)
    return join_as("Hero_Engraving", objs, parent)


def engrave_side(labels, font, material, parent, radius=1.4745, y=-0.035, size=0.078,
                 span_deg=70, accent=None, accent_mat=None):
    objs = []
    n = len(labels)
    for k, lab in enumerate(labels):
        phi = math.radians(-span_deg / 2 + span_deg * k / (n - 1))
        g = glyph(lab, size, font, accent_mat if lab == accent else material)
        normal = Vector((math.sin(phi), 0.0, math.cos(phi)))
        up = Vector((0.0, 1.0, 0.0))     # reads upright while the lens faces the viewer
        right = up.cross(normal)
        basis = Matrix((right, up, normal)).transposed().to_4x4()
        basis.translation = normal * radius + Vector((0.0, y, 0.0))
        g.matrix_world = basis
        objs.append(g)
    return join_as("Hero_Stops", objs, parent)


# ================================================================ the hero

def build_hero():
    root = empty("Hero")
    M = dict(
        black=pbr_material("Anodised black", color=(0.012, 0.012, 0.014), metallic=0.6, roughness=0.38),
        satin=pbr_material("Satin black", color=(0.02, 0.02, 0.022), metallic=0.2, roughness=0.62),
        rubber=pbr_material("Grip rubber", color=(0.018, 0.018, 0.018), roughness=0.78),
        blade=pbr_material("Blade gunmetal", color=(0.05, 0.05, 0.056), metallic=1.0, roughness=0.3),
        brushed=pbr_material("Brushed aluminium", color=(0.62, 0.62, 0.64), metallic=1.0, roughness=0.28),
        chrome=pbr_material("Mount chrome", color=(0.85, 0.85, 0.86), metallic=1.0, roughness=0.1),
        paint=pbr_material("Engraving paint", color=(0.92, 0.91, 0.88), roughness=0.5),
        gold=pbr_material("Accent gold", color=(0.92, 0.62, 0.26), metallic=1.0, roughness=0.22,
                          emission=(1.0, 0.55, 0.2), emission_strength=0.6),
        red=pbr_material("Index red", color=(0.85, 0.05, 0.03), roughness=0.4,
                         emission=(1.0, 0.08, 0.04), emission_strength=0.8),
        glass=pbr_material("Front element", color=(0.9, 0.95, 1.0), roughness=0.02, transmission=1.0, ior=1.52),
        rear_glass=pbr_material("Rear element", color=(0.75, 0.85, 1.0), roughness=0.03, transmission=1.0, ior=1.6),
    )
    font = bpy.data.fonts.load(FONT)
    lens_to_reel_parts(root, M, font)
    return root


def lathe_part(name, lens_profile, reel_profile, material, parent, f0, f1, dy, steps=128):
    assert len(lens_profile) == len(reel_profile), name
    v, f = lathe(lens_profile, steps)
    obj = mesh_from(name, v, f, material, parent)
    add_reel_key(obj, lathe(reel_profile, steps)[0])
    morph(obj, f0, f1)
    telescope(obj, dy)
    return obj


def shrink_away(obj, f0, f1, to=(0.0, 0.0, 0.0)):
    """Parts with no reel counterpart pull into the film roll and vanish."""
    loc = tuple(obj.location)
    sc = tuple(obj.scale)
    keys(obj, "location", [(0, loc), (f0, loc), (f1, to), (END, to)])
    keys(obj, "scale", [(0, sc), (f0, sc), (f1, (0.001, 0.001, 0.001)), (END, (0.001, 0.001, 0.001))])


SPOKE_Y = (-0.275, -0.245)


def best_spoke_match(outer0, inner0):
    """Search how a blade should map onto its spoke so vertices travel the
    least during the morph (less travel = no crossing = a clean mechanical
    move). Evaluated for blade 0; all blades are rotations of it."""
    open_rot = Matrix.Rotation(math.radians(-OPEN_DEG), 4, "Y")
    pivot = Vector((PIVOT_R, 0.0))
    o = [p - pivot for p in outer0]
    n = [p - pivot for p in inner0]
    blade_v, _ = strip_solid([(p.x, p.y) for p in o], [(p.x, p.y) for p in n], -0.006, 0.006)
    best = None
    for reverse in (False, True):
        for flip in (False, True):
            for hinge_r in (0.6, 0.9, 1.2, 1.5):
                for off_deg in range(-60, 61, 10):
                    for swirl_deg in range(-120, 121, 15):
                        theta = math.radians(off_deg)
                        so, si = spoke_polylines(theta, reverse=reverse, flip=flip)
                        sv, _ = strip_solid([(p.x, p.y) for p in so], [(p.x, p.y) for p in si], *SPOKE_Y)
                        end_loc = Vector((math.cos(theta) * hinge_r, 0.0, math.sin(theta) * hinge_r))
                        to_local = (Matrix.Translation(end_loc) @ Matrix.Rotation(math.radians(swirl_deg), 4, "Y") @ open_rot).inverted()
                        cost = sum((Vector(b) - to_local @ Vector(v)).length_squared for b, v in zip(blade_v, sv))
                        if best is None or cost < best[0]:
                            best = (cost, dict(reverse=reverse, flip=flip, hinge_r=hinge_r,
                                               offset=theta, swirl=math.radians(swirl_deg)))
    return best[1]


def lens_to_reel_parts(root, M, font):
    # ---- blades → spokes ------------------------------------------------
    outer0, inner0 = blade_polylines()
    params = best_spoke_match(outer0, inner0)
    print("[scroll-cinema] blade→spoke match:", params)
    open_rot = Matrix.Rotation(math.radians(-OPEN_DEG), 4, "Y")    # web holds the iris open
    swirl = params["swirl"]                                         # each blade turns about its hinge
    spoke_y0, spoke_y1 = SPOKE_Y
    for i in range(N_BLADES):
        ang = i * math.tau / N_BLADES
        ca, sa = math.cos(ang), math.sin(ang)
        pivot = Vector((PIVOT_R * ca, PIVOT_R * sa))
        rot2 = lambda p: Vector((p.x * ca - p.y * sa, p.x * sa + p.y * ca))
        o = [rot2(p) - pivot for p in outer0]
        n = [rot2(p) - pivot for p in inner0]
        verts, faces = strip_solid([(p.x, p.y) for p in o], [(p.x, p.y) for p in n], -0.006, 0.006)
        pv = empty(f"Hero_BladePivot_{i:02d}", root, (pivot.x, i * 0.007, pivot.y))
        blade = mesh_from(f"Hero_Blade_{i:02d}", verts, faces, M["blade"], pv, smooth=False)

        # reel state, expressed in the blade's local frame at the end pose
        theta = ang + params["offset"]
        so, si = spoke_polylines(theta, reverse=params["reverse"], flip=params["flip"])
        # the pivot ends ON its spoke, so each blade turns about its own hinge
        # into place instead of all blades crowding the centre
        end_loc = Vector((math.cos(theta) * params["hinge_r"], 0.0, math.sin(theta) * params["hinge_r"]))
        end_rot = Matrix.Rotation(swirl, 4, "Y")
        to_local = (Matrix.Translation(end_loc) @ end_rot @ open_rot).inverted()
        sv, _ = strip_solid([(p.x, p.y) for p in so], [(p.x, p.y) for p in si], spoke_y0, spoke_y1)
        reel_local = [tuple(to_local @ Vector(p)) for p in sv]
        if i == 0:
            blade0_reel = reel_local
        else:   # 9-fold symmetry: blade i's reel shape = blade 0's turned by its angle
            turn = Matrix.Rotation(-ang, 4, "Y")    # Blender +Y turns x→−z; pivots go x→+z
            drift = max((Vector(a) - turn @ Vector(b)).length for a, b in zip(reel_local, blade0_reel))
            assert drift < 1e-4, f"blade {i} breaks symmetry ({drift:.4f})"
        add_reel_key(blade, reel_local)
        # choreography: (40–56) the open blades slide out in front of the lens,
        # (58–86) there, in a clear plane, they swirl inward and straighten into
        # spokes, (86–102) the finished spokes slide back into the reel.
        front_y = -0.95                     # in front of the telescoped front ring
        morph(blade, 58, 86)
        start = (pivot.x, i * 0.007, pivot.y)
        keys(pv, "location", [(0, start), (40, start), (56, (pivot.x * 1.04, front_y, pivot.y * 1.04)),
                              (86, (end_loc.x, front_y, end_loc.z)), (102, tuple(end_loc)), (END, tuple(end_loc))])
        keys(pv, "rotation_euler", [(0, (0, 0, 0)), (58, (0, 0, 0)), (86, (0, swirl, 0)), (END, (0, swirl, 0))])

    # ---- barrel rings → flanges ------------------------------------------
    lathe_part("Hero_Barrel",
               [(1.06, -0.33), (1.40, -0.33), (1.45, -0.29), (1.45, -0.15), (1.41, -0.13), (1.06, -0.13)],
               [(1.70, -0.285), (1.97, -0.285), (2.00, -0.275), (2.00, -0.245), (1.97, -0.235), (1.70, -0.235)],
               M["black"], root, 34, 76, -0.40)
    lathe_part("Hero_Body",
               [(1.06, 0.42), (1.43, 0.42), (1.43, 0.47), (1.36, 0.58), (1.22, 0.63), (1.06, 0.63)],
               [(0.38, 0.24), (1.97, 0.24), (2.00, 0.25), (2.00, 0.275), (1.97, 0.285), (0.38, 0.285)],
               M["black"], root, 34, 76, 0.40)
    lathe_part("Hero_Mount",
               [(0.96, 0.63), (1.19, 0.63), (1.19, 0.66), (1.16, 0.73), (0.96, 0.73)],
               [(0.20, -0.27), (0.38, -0.27), (0.38, 0.20), (0.36, 0.27), (0.20, 0.27)],
               M["chrome"], root, 38, 80, 0.55)
    lathe_part("Hero_Baffle",
               [(1.00, -0.13), (1.06, -0.13), (1.06, 0.63), (1.00, 0.63)],
               [(0.39, -0.20), (0.40, -0.20), (0.40, 0.20), (0.39, 0.20)],
               M["satin"], root, 34, 76, 0.0, steps=96)
    lathe_part("Hero_ApertureRing",
               [(1.38, -0.13), (1.465, -0.125), (1.47, -0.115), (1.47, 0.045), (1.465, 0.055), (1.38, 0.06)],
               [(1.20, -0.10), (1.25, -0.10), (1.25, -0.09), (1.25, 0.09), (1.25, 0.10), (1.20, 0.10)],
               M["black"], root, 36, 64, -0.12)
    lathe_part("Hero_Band",
               [(1.40, 0.06), (1.458, 0.062), (1.458, 0.108), (1.40, 0.11)],
               [(1.20, -0.05), (1.24, -0.05), (1.24, 0.05), (1.20, 0.05)],
               M["brushed"], root, 36, 64, 0.0)

    # ---- focus grip → film roll -----------------------------------------
    gv, gf = grip_mesh(1.475, 1.445, 1.40, 0.12, 0.42, 0.022)
    grip = mesh_from("Hero_Grip", gv, gf, M["rubber"], root)
    add_reel_key(grip, grip_mesh(1.55, 1.53, 0.40, -0.22, 0.22, 0.0, groove=0.004)[0])
    morph(grip, 36, 80)

    # ---- glass → hub cap / gone -----------------------------------------
    fv, ff = ellipsoid(1.1, 0.16, 1.1, -0.16)
    front = mesh_from("Hero_Glass", fv, ff, M["glass"], root)
    add_reel_key(front, ellipsoid(0.30, 0.05, 0.30, -0.30)[0])
    morph(front, 30, 70)
    telescope(front, -0.55)
    rv, rf = ellipsoid(0.98, 0.08, 0.98, 0.55, u=48, v=16)
    rear = mesh_from("Hero_Glass_Rear", rv, rf, M["rear_glass"], root)
    add_reel_key(rear, ellipsoid(0.18, 0.02, 0.18, 0.0, u=48, v=16)[0])
    morph(rear, 30, 70)
    telescope(rear, 0.2)

    # ---- bayonet tabs → hub drive keys -------------------------------------
    for k in range(3):
        a = k * math.tau / 3 + 0.4
        v, f = strip_solid([(-0.5, -0.5), (0.5, -0.5)], [(-0.5, 0.5), (0.5, 0.5)], -0.5, 0.5)
        tab = mesh_from(f"Hero_Tab_{k}", v, f, M["chrome"], root, smooth=False)
        start_loc = (math.sin(a) * 1.08, 0.745, math.cos(a) * 1.08)
        end_loc = (math.sin(a) * 0.19, 0.0, math.cos(a) * 0.19)
        tab.rotation_euler = (0, a, 0)
        keys(tab, "location", [(0, start_loc), (12, start_loc), (40, (start_loc[0], 1.3, start_loc[2])),
                               (80, (end_loc[0], 1.0, end_loc[2])), (114, end_loc), (END, end_loc)])
        keys(tab, "scale", [(0, (0.34, 0.035, 0.08)), (40, (0.34, 0.035, 0.08)),
                            (80, (0.06, 0.5, 0.05)), (END, (0.06, 0.5, 0.05))])

    # ---- accents follow the front ring -------------------------------------
    bpy.ops.mesh.primitive_torus_add(major_radius=1.385, minor_radius=0.011, major_segments=160, minor_segments=8)
    ring = bpy.context.object
    ring.name, ring.parent = "Hero_Accent", root
    ring.rotation_euler = (math.pi / 2, 0, 0)
    ring.data.materials.append(M["gold"])
    for poly in ring.data.polygons:
        poly.use_smooth = True
    s = 1.985 / 1.385
    keys(ring, "location", [(0, (0, -0.336, 0)), (12, (0, -0.336, 0)), (40, (0, -0.736, 0)),
                            (90, (0, -0.6875, 0)), (114, (0, -0.2875, 0)), (END, (0, -0.2875, 0))])
    keys(ring, "scale", [(0, (1, 1, 1)), (34, (1, 1, 1)), (76, (s, s, 1)), (END, (s, s, 1))])

    eng = engrave_front("RESUL ÇETİN · SCROLL CINEMA 50mm 1:1.4 · Ø62 · MADE TO MOVE", font, M["paint"], root)
    s = 1.85 / 1.215
    ly = -0.2865 - s * -0.3345                 # keeps the text on the rim's front face
    keys(eng, "location", [(0, (0, 0, 0)), (12, (0, 0, 0)), (40, (0, -0.40, 0)),
                           (90, (0, ly - 0.40, 0)), (114, (0, ly, 0)), (END, (0, ly, 0))])
    keys(eng, "scale", [(0, (1, 1, 1)), (34, (1, 1, 1)), (76, (s, s, s)), (END, (s, s, s))])

    # ---- parts with no reel counterpart ------------------------------------
    stops = engrave_side(["16", "8", "4", "2.8", "2", "1.4"], font, M["paint"], root,
                         accent="1.4", accent_mat=M["gold"])
    shrink_away(stops, 30, 58)
    v, f = ellipsoid(0.018, 0.018, 0.018, 0.0, u=16, v=8)
    dot = mesh_from("Hero_Index", v, f, M["red"], root)
    dot.location = (0, 0.085, 1.462)
    shrink_away(dot, 30, 58)


# ================================================================ output

def stats():
    tris = 0
    deps = bpy.context.evaluated_depsgraph_get()
    for obj in bpy.context.scene.objects:
        if obj.type == "MESH":
            me = obj.evaluated_get(deps).to_mesh()
            me.calc_loop_triangles()
            tris += len(me.loop_triangles)
            obj.evaluated_get(deps).to_mesh_clear()
    return tris


def export_glb(path, draco=True):
    bpy.context.scene.frame_set(0)
    kwargs = dict(
        filepath=path, export_format="GLB", export_yup=True, export_apply=False,
        export_materials="EXPORT",
        export_animations=True, export_animation_mode="SCENE", export_anim_scene_split_object=False,
        export_frame_range=True, export_anim_slide_to_zero=True, export_optimize_animation_size=True,
        export_morph=True, export_morph_normal=True, export_morph_animation=True,
    )
    if draco:
        kwargs.update(export_draco_mesh_compression_enable=True, export_draco_mesh_compression_level=6,
                      export_draco_position_quantization=14, export_draco_normal_quantization=10)
    bpy.ops.export_scene.gltf(**kwargs)


def setup_render(path_hint):
    scene = bpy.context.scene
    cam = bpy.data.objects.new("PreviewCam", bpy.data.cameras.new("PreviewCam"))
    scene.collection.objects.link(cam)
    cam.location = (3.0, -6.2, 2.0)
    cam.rotation_euler = (Vector((0, 0, 0)) - cam.location).to_track_quat("-Z", "Y").to_euler()
    cam.data.lens = 50
    scene.camera = cam
    for loc, energy in (((4, -5, 5), 1200), ((-6, 1, 3), 400), ((0, 6, -2), 500), ((0, -6, -3), 250)):
        ld = bpy.data.lights.new("PreviewLight", "AREA")
        ld.energy, ld.size = energy, 5
        lo = bpy.data.objects.new("PreviewLight", ld)
        lo.location = loc
        lo.rotation_euler = (Vector((0, 0, 0)) - Vector(loc)).to_track_quat("-Z", "Y").to_euler()
        scene.collection.objects.link(lo)
    world = bpy.data.worlds.new("PreviewWorld")
    if world.node_tree is None:
        world.use_nodes = True
    world.node_tree.nodes["Background"].inputs["Color"].default_value = (0.02, 0.02, 0.025, 1)
    scene.world = world
    for engine in ("BLENDER_EEVEE", "BLENDER_EEVEE_NEXT", "BLENDER_WORKBENCH"):
        try:
            scene.render.engine = engine
            break
        except TypeError:
            continue
    scene.render.resolution_x, scene.render.resolution_y = 640, 480
    for obj in bpy.data.objects:                  # EEVEE renders transmission milky; hide glass
        if obj.name.startswith("Hero_Glass"):
            obj.hide_render = True


def set_iris(open_amt):
    for obj in bpy.data.objects:
        if obj.name.startswith("Hero_Blade_"):
            obj.rotation_euler = (0, -open_amt * math.radians(OPEN_DEG), 0)


def main():
    args = parse_args()
    reset_scene()
    build_hero()
    set_iris(0)
    tris = stats()
    export_glb(args.out, draco=not args.no_draco)
    print(f"[scroll-cinema] exported {args.out} — {tris:,} triangles")
    if args.video:
        setup_render(args.out)
        scene = bpy.context.scene
        # preview only: the web opens the iris just before the morph — show it
        for obj in bpy.data.objects:
            if obj.name.startswith("Hero_Blade_"):
                keys(obj, "rotation_euler", [(0, (0, 0, 0)), (14, (0, -math.radians(OPEN_DEG), 0))])
        scene.render.resolution_x, scene.render.resolution_y = 960, 720
        settings = scene.render.image_settings
        if hasattr(settings, "media_type"):          # Blender 5: video lives behind media_type
            settings.media_type = "VIDEO"
        settings.file_format = "FFMPEG"
        scene.render.ffmpeg.format = "MPEG4"
        scene.render.ffmpeg.codec = "H264"
        scene.render.ffmpeg.constant_rate_factor = "HIGH"
        scene.render.filepath = args.video
        bpy.ops.render.render(animation=True)
        print(f"[scroll-cinema] video {args.video}")
        return
    if args.preview or args.frames:
        setup_render(args.out)
        scene = bpy.context.scene
        if args.preview:
            set_iris(0.4)
            scene.frame_set(0)
            scene.render.filepath = args.preview
            bpy.ops.render.render(write_still=True)
        if args.frames:
            os.makedirs(args.frames, exist_ok=True)
            set_iris(1.0)                            # the web holds the iris open during the morph
            frames = range(0, END + 1, 10)
            if args.front:                           # straight-on view of the blade section
                cam = scene.camera
                cam.location = (0, -7.5, 0)
                cam.rotation_euler = (Vector((0, 0, 0)) - cam.location).to_track_quat("-Z", "Y").to_euler()
                frames = range(50, 106, 6)
            for f in frames:
                scene.frame_set(f)
                scene.render.filepath = os.path.join(args.frames, f"f{f:03d}.png")
                bpy.ops.render.render(write_still=True)
            scene.frame_set(END)
            scene.render.resolution_x, scene.render.resolution_y = 1400, 1050
            scene.render.filepath = os.path.join(args.frames, "reel_large.png")
            bpy.ops.render.render(write_still=True)
            print(f"[scroll-cinema] storyboard frames in {args.frames}")


main()
